### ISSUE TITLE
Error using some websites

### ISSUE THREAD

**Issue by fialhorenato** [hugodias/seohelper#1]
There's an error when try to search for some websites such as `www.google.com.br` or `www.altaenergia.com.br`. 

``` javascript
TypeError: Cannot call method 'replace' of null
  at Scraper.highlightKeywords (/vagrant/Projetos/seohelper2/seohelper/modules/scraper.coffee:73:13)
  at Scraper.process (/vagrant/Projetos/seohelper2/seohelper/modules/scraper.coffee:126:21)
  at /vagrant/Projetos/seohelper2/seohelper/modules/scraper.coffee:177:13
  at Request._callback (/vagrant/Projetos/seohelper2/seohelper/modules/scraper.coffee:106:9)
  at Request.self.callback (/vagrant/Projetos/seohelper2/seohelper/node_modules/request/request.js:198:22)
  at Request.emit (events.js:98:17)
  at Request.<anonymous> (/vagrant/Projetos/seohelper2/seohelper/node_modules/request/request.js:1082:10)
  at Request.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (/vagrant/Projetos/seohelper2/seohelper/node_modules/request/request.js:1009:12)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)
```

**Comment by hugodias** [comment]
Fixed on #2
